# Generated by Django 3.0.5 on 2020-04-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=300)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=300)),
                ('description', models.TextField(default='')),
                ('topics_count', models.IntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='api.Category')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.IntegerField(default=4)),
                ('title', models.CharField(default='title', max_length=300)),
                ('description', models.TextField(default='')),
                ('author', models.CharField(default='author', max_length=300)),
                ('date', models.DateField(default='February 4, 2016 10:13:00')),
                ('replies', models.IntegerField(default=4)),
                ('views', models.IntegerField(default=201)),
                ('last_author', models.CharField(default='last author', max_length=300)),
                ('last_date', models.DateField(default='April 17, 2020 11:17:00')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.Discussion')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='content', max_length=300)),
                ('author', models.CharField(default='author', max_length=300)),
                ('date', models.DateField(default='May 2, 2016 10:13:00')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Topic')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
