# Generated by Django 3.0.4 on 2020-04-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='discussion',
        ),
    ]
