# Generated by Django 3.0.4 on 2020-04-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_topic_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='discussion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.Discussion'),
        ),
    ]
