# Generated by Django 3.0.5 on 2020-04-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_topic_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='api.Discussion'),
        ),
    ]
